### ISSUE TITLE
Event no longer passing after updating to 2.1.3, 2.1.4

### ISSUE THREAD

**Issue by skawaguchi** [RyanMullins/angular-hammer#21]
I'm using angular-hammer like this:
        
        <a ng-repeat="someItem in someList" hm-tap="myFunction( $event, someItem )">My Link</a>

The directive used to pass `$event`, but it no longer does in 2.1.3 or 2.1.4.

I know that the usage doesn't really follow your examples. I wasn't sure how else to get the object in my repeated into the tap function.

**Comment by RyanMullins** [comment]
I think I fixed this today with v2.1.5. Take a look using that and let me know.

**Comment by skawaguchi** [comment]
I update the pen with 2.1.5 and the event still isn't being passed.

**Comment by equilerex** [comment]
Same here... cant pass $event on v2.1.9

**Comment by RyanMullins** [comment]
So the reason you weren't getting the $event is because i wasn't defining a `locals` object and passing it to the handler expression function returned by [$parse](http://devdocs.io/angular/ng/service/$parse). Please reopen if you find the fix isn't working.
